packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  next: ^16.1.1
  "@orpc/server": ^1.12.2
  "@orpc/client": ^1.12.2
  "@orpc/openapi": ^1.12.2
  "@orpc/zod": ^1.12.2
  better-auth: ^1.4.18
  drizzle-orm: ^0.45.1
  "@types/pg": ^8.16.0
  drizzle-zod: ^0.8.3
  vitest: ^3.0.0
